filter {
  ########################
  # ECS Field Validation #
  ########################

  # ----------------------
  # event.type
  # ----------------------
  if [event][type] and !([event][type] in ["access","admin","change","creation","deletion","device","discovery","dns","driver","file","host","iam","installation","malware","network","process","registry","session","user"]) {
    mutate { remove_field => ["[event][type]"] }
    mutate { add_tag => ["event.type-invalid_field_value"] }
  }

  # ----------------------
  # event.category
  # ----------------------
  if [event][category] and !([event][category] in ["authentication","database","driver","file","host","iam","malware","network","process","registry","session","user"]) {
    mutate { remove_field => ["[event][category]"] }
    mutate { add_tag => ["event.category-invalid_field_value"] }
  }

  # ----------------------
  # event.kind
  # ----------------------
  if [event][kind] and !([event][kind] in ["alert","event","state"]) {
    mutate { remove_field => ["[event][kind]"] }
    mutate { add_tag => ["event.kind-invalid_field_value"] }
  }

  # ----------------------
  # event.outcome
  # ----------------------
  if [event][outcome] and !([event][outcome] in ["success","failure","unknown"]) {
    mutate { remove_field => ["[event][outcome]"] }
    mutate { add_tag => ["event.outcome-invalid_field_value"] }
  }
}
