################# ENRICH #################
- pipeline.id: enrichments
  pipeline.batch.delay: 50
  pipeline.batch.size: 1000
  pipeline.workers: 64
  # queue.type: persisted
  # queue.max_bytes: 8192mb
  path.config: "${LOGSTASH_HOME}/config/enrichments/{*}.conf"

################# OUTPUT #################
- pipeline.id: elastic_output
  path.config: "${LOGSTASH_HOME}/config/outputs/elastic_output.conf"
  pipeline.batch.delay: 50
  pipeline.batch.size: 2000
  # pipeline.workers: 1
- pipeline.id: s3_output
  path.config: "${LOGSTASH_HOME}/config/outputs/s3_output.conf"
  pipeline.batch.delay: 50
  pipeline.batch.size: 2000
  # pipeline.workers: 1
- pipeline.id: nc4_output
  path.config: "${LOGSTASH_HOME}/config/outputs/nc4_output.conf"
  pipeline.workers: 1

############### INPUTS & PROCESSORS ###############
