# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "aws" }
    add_field => { "[event][dataset]" => "aws.waf" }
  }
  mutate {
    gsub => [ 
      "message", "(?i)rulegrouplist\[\]\.", "rulegrouplist",
      "message", "(?i)httprequest\.", "httprequest"
    ]
  }
  json {
    source => "message"
    target => "aws"
  }
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  
  mutate {
    rename => { 
      "[aws][class_name]" => "[event][kind]"
      "[aws][disposition]" => "[event][outcome]"
      "[aws][action]" => "[event][action]"
      "[aws][http_request][referrer]" => "[http][request][referrer]"
      "[aws][http_request][url][path]" => "[url][path]"
      "[aws][http_request][url][hostname]" => "[url][domain]"
      "[aws][http_request][http_method]" => "[http][request][method]"
      "[aws][http_request][user_agent]" => "[user_agent][name]"
      "[aws][http_request][args]" => "[process][args]"
      "[aws][http_request][version]" => "[http][version]"
      "[aws][category_uid]" => "[rule][category]"
      "[aws][time_dt]" => "[event][created]"
      "[aws][unmapped][httprequest.scheme]" => "[url][scheme]"
      "[aws][unmapped][rulegrouplistterminatingrule.ruleid]" => "[rule][id]"
      "[aws][unmapped][httprequest.fragment]" => "[url][fragment]"
      "[aws][unmapped][ja3fingerprint]" => "[tls][client][ja3]"
      "[aws][unmapped][rulegrouplistrulegroupid]" => "[rule][ruleset]"
      "[aws][src_endpoint][svc_name]" => "[cloud][machine][type]"
      "[aws][src_endpoint][uid]" => "[cloud][instance][id]"
      "[aws][src_endpoint][ip]" => "[destination][ip]"
      "[aws][category_name]" => "[event][category]"
      "[aws][metadata][product][feature][uid]" => "[cloud][instance][name]"
      "[aws][firewall_rule][uid]" => "[rule][name]"
      "[aws][severity]" => "[event][severity_name]"
      "[aws][severity_id]" => "[event][severity]"
      "[aws][type_name]" => "[event][code]"
    }
  }
  mutate {
    join => { "[aws][http_request][x_forwarded_for][array]" => "," }
  }
  mutate {
    split => { "[aws][http_request][x_forwarded_for][array]" => "," }
  }
  mutate {
    add_field => {
      "[network][forwarded_ip]" => "%{[aws][http_request][x_forwarded_for][array][0]}"
    }
  }	  
  grok {
    match => { "[cloud][instance][id]" => "^(?<[cloud][account][id]>.*?)-" }
  }
  # "[event][created]" = 1744115336775
  date {
    match => ["[event][created]" , UNIX_MS ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
   }
   
  mutate {
    remove_field => [ "aws" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
