# Copyright [2023] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[cloud][provider]" => "aws" }
    add_field => { "[event][module]" => "aws" }
    add_field => { "[event][dataset]" => "aws.firewall" }
  }
  json {
    source => "message"
    target => "aws"
  }
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => { 
      "[aws][firewall_name]" => "[log][source][hostname]"
      "[aws][availability_zone]" => "[cloud][availability_zone]"
      "[aws][event_timestamp]" => "[event][created]" 
      "[aws][event][alert][severity]" => "[event][severity]"
      "[aws][event][alert][signature_id]" => "[rule][id]"
      "[aws][event][alert][action]" => "[event][action]"
      "[aws][event][alert][signature]" => "[rule][name]"
      "[aws][event][alert][category]" => "[rule][category]"
      "[aws][event][flow_id]" => "[event][id]"
      "[aws][event][direction]" => "[network][direction]"
      "[aws][event][src_ip]" => "[source][ip]"
      "[aws][event][proto]" => "[network][transport]"
      "[aws][event][event_type]" => "[event][type]"
      "[aws][event][dest_ip]" => "[destination][ip]"
      "[aws][event][verdict][action]" => "[event][outcome]"
      "[aws][event][pkt_src]" => "[observer][egress][interface][name]"
      "[aws][event][dest_port]" => "[destination][port]"
      "[aws][event][src_port]" => "[source][port]"     
      "[aws][event][app_proto]" => "[network][protocol]"
      "[aws][event][netflow][end]" => "[event][end]"	  
      "[aws][event][netflow][start]" => "[event][start]"
      "[aws][event][netflow][bytes]" => "[network][bytes]"
      "[aws][event][netflow][reason]" => "[event][reason]"
      "[aws][event][netflow][state]" => "[event][action]"
      "[aws][event][netflow][pkts]" => "[network][packets]"

    }  
  }
  # "[event][created]" # "1743699655"
  date {
    match => ["[event][created]" , UNIX ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
   }
  # "[event][end]" # "2025-04-03t17:36:34.180755+0000",	  
  date {
    match => ["[event][end]" , ISO8601 ]
    timezone => "GMT"
    locale => "en"
    target => "[event][end]"
    tag_on_failure => "_dateparsefailure_ee"
   }
  # "[event][start]" # "2025-04-03t17:36:34.061010+0000",
  date {
    match => ["[event][start]" , ISO8601 ]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
    tag_on_failure => "_dateparsefailure_es"
   } 
  
  mutate {
    # remove_field => [ "aws" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
