# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "aws" }
    add_field => { "[event][dataset]" => "aws.vpcflow" }
  }
  
  json {
    source => "message"
    target => "aws"
  }
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => { 
      "[aws][cloud][region]" => "[cloud][region]"
      "[aws][cloud][account][uid]" => "[cloud][account][id]"
      "[aws][cloud][zone]" => "[cloud][availability_zone]"
      "[aws][cloud][provider]" => "[cloud][provider]"
      "[aws][connection_info][direction]" => "[network][direction]"
      "[aws][connection_info][protocol_ver]" => "[network][type]"
      "[aws][time_dt]" => "[event][created]"
      "[aws][start_time_dt]" => "[event][start]"
      "[aws][end_time_dt]" => "[event][end]"
      "[aws][category_name]" => "[event][category]"
      "[aws][disposition]" => "[event][outcome]"
      "[aws][action]" => "[event][action]"
      "[aws][status_code]" => "[event][code]"
      "[aws][severity]" => "[event][severity_name]"
      "[aws][traffic][bytes]" => "[network][bytes]"
      "[aws][traffic][packets]" => "[network][packets]"
      "[aws][dst_endpoint][port]" => "[destination][port]"
      "[aws][dst_endpoint][ip]" => "[destination][ip]"
      "[aws][dst_endpoint][src_endpoint][port]" => "[source][port]" 
      "[aws][dst_endpoint][src_endpoint][ip]" => "[source][ip]"
      "[aws][src_endpoint][interface_uid]" => "[cloud][interface][id]"
      "[aws][src_endpoint][subnet_uid]" => "[cloud][network][name]"
      "[aws][src_endpoint][vpc_uid]" => "[cloud][vpc_uid]"
    }
  }
      # "[event][created]" # 1743709148000
  date {
    match => ["[event][created]","UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
      # "[event][start]" # 1743709148000
  date {
    match => ["[event][start]","UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
    tag_on_failure => "_dateparsefailure_es"
  }
      # "[event][end]" # 1743709172000
  date {
    match => ["[event][end]","UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][end]"
    tag_on_failure => "_dateparsefailure_ee"
  }
  
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
