# Copyright [2021] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => ["event", "host", "log" ]
  } 
  mutate {
    add_field => { 
      "[event][module]" => "sap" 
      "[event][dataset]" => "sap.t-codes" 
    }
  }
  mutate {
    rename => {
      "[timestamp]" => "[event][created]"
      "[reason_id]" => "[event][reason]"
      "[agent][type]" => "[agent][type]"
      "[agent][name]" => "[agent][name]"
      "[client_pc]" => "[source][ip]"
      "[username]" => "[user][name]"
      "[log_client]" => "[group][id]"
      "[edm_data][log_sapgui][value_header][0][pprogram]" => "[process][name]"
      "[edm_data][log_sapgui][value_header][0][gui_title]" => "[rule][name]"
      "[edm_data][log_sapgui][value_header][0][tcode]" => "[rule][id]"	  
      "[trx_name]" => "[rule][description]"
      "[tid]" => "[rule][category]"
      "[sysid]" =>  "[host][id]"
      "[technology]" => "[host][os][type]"
      "[host_name]" => "[host][hostname]"
      "[log][source][ip]" => "[log][source][ip]"	
      "[log][source][hostname]" => "[log][source][hostname]"	  
    }
  }
  mutate {
    strip => ["[event][created]"]
  }

  # "[event][created]" = "20240108175253.178 "
  date {
    match => ["[event][created]", "yyyyMMddHHmmss.SSS" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
  }
  mutate {
    remove_field => ["[edm_data]", "[edm_data_enc]"]
  } 
}
output {
  pipeline { send_to => [enrichments] }
}
