# Copyright [2021] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate{  
    remove_field => [ "host", "event", "file" ]   
  }
  mutate {
    add_field => { "[event][module]" => "infoblox" }
    add_field => { "[event][dataset]" => "infoblox.dns_query" }
    add_field => { "[log][source][hostname]" => "api_infoblox_dns_query" }
    tag_on_failure => "_mutate_error_1"
  }
  json {
    source => "message"
    target => "tmp"
  }
  mutate {
    rename => { 
      "[tmp][category]" => "[event][category]"
      "[tmp][country]" => "[source][geo][country_iso_code]"
      "[tmp][qip]" => "[source][ip]"
      "[tmp][dhcp_fingerprint]" => "[source][user][hash]"
      "[tmp][user]" => "[source][user][name]"
      "[tmp][mac_address]" => "[source][mac]"
      "[tmp][os_version]" => "[source][os][version]"
      "[tmp][feed_name]" => "[rule][name]"
      "[tmp][feed_type]" => "[rule][category]"
      "[tmp][qname]" => "[tmp][dns][answers][name]"
      "[tmp][qtype]" => "[dns][question][type]"
      "[tmp][rcode]" => "[dns][answers][type]"
      "[tmp][rdata]" => "[dns][answers][data]"
      "[tmp][severity]" => "[event][severity_name]"
      "[tmp][tclass]" => "[threat][framework]"
    }
    tag_on_failure => "_mutate_error_2"
  }
  grok {
    match => { "[tmp][dns][answers][name]" => "^(?<[dns][answers][name]>.*?)(\.)?$" }
  }
  mutate {
    copy => { 
      "[dns][answers][data]" => "[destination][ip]"
      "[dns][answers][name]" => "[destination][address]"
    }
    tag_on_failure => "_mutate_error_3"
  }
  if [source][user][hash] == "" {
    mutate {
      remove_field => [ "[source][user][hash]" ]
    }    
  }
  if [source][os][version] == "" {
    mutate {
      remove_field => [ "[source][os][version]" ]
    }
  }
  if [event][category] == "" {
    mutate {
      remove_field => [ "[event][category]" ]
    }
  } 
  date {
    match => ["[tmp][event_time]", "ISO8601"]
    timezone => "GMT"
    locale => "ec"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
