# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "aws" }
    add_field => { "[event][dataset]" => "aws.route53" }
  }
  json {
    source => "message"
    target => "aws"
  }
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => { 
      "[aws][disposition]" => "[event][outcome]"
      "[aws][firewall_rule]" => "[rule][name]"
      "[aws][class_name]" => "[event][kind]"
      "[aws][category_name]" => "[event][category]"
      "[aws][rcode]" => "[event][code]"
      "[aws][action]" => "[event][action]"	  
      "[aws][category_uid]" => "[rule][category]"
      "[aws][type_name]" => "[event][code]"
      "[aws][metadata][product][feature][name]" => "[event][type]"
      "[aws][severity_id]" => "[event][severity]"
      "[aws][rcode_id]" => "[event][id]"
      "[aws][connection_info][direction]" => "[network][direction]"
      "[aws][connection_info][protocol_name]" => "[network][transport]"
      "[aws][cloud][account][uid]" => "[cloud][account][id]"
      "[aws][cloud][region]" => "[cloud][region]"
      "[aws][src_endpoint][vpc_uid]" => "[source][domain]"
      "[aws][src_endpoint][ip]" => "[source][ip]"
      "[aws][src_endpoint][instance_uid]" => "[source][address]"
      "[aws][src_endpoint][port]" => "[source][port]"
      "[aws][severity]" => "[event][severity_name]"
      "[aws][time_dt]" => "[event][created]"

      "[aws][query][hostname]" => "[dns][question][name]"
      "[aws][query][type]" => "[dns][type]" 
      "[aws][query][class]" => "[dns][question][class]"
	  
      "[aws][answers][array][0][type]" => "[dns][answers][type]"
      "[aws][answers][array][0][rdata]" => "[dns][answers][data]"
      "[aws][answers][array][0][class]" => "[dns][answers][class]"
    }
  }
  if [aws][dst_endpoint] {
    mutate {
      rename => { 
       "[aws][dst_endpoint][instance_uid]" => "[destination][address]"
       "[aws][dst_endpoint][interface_uid]" => "[observer][egress][interface][id]"
      }
    }
  }
  if [aws][answers][array][1] {
    mutate {
      merge => { 
	    "[dns][answers][type]" => "[aws][answers][array][1][type]"
	    "[dns][answers][data]" => "[aws][answers][array][1][rdata]"    
	    "[dns][answers][class]" => "[aws][answers][array][1][class]"    
	  }
    }
  }
  if [aws][answers][array][2] {
    mutate {
      merge => { 
	    "[dns][answers][type]" => "[aws][answers][array][2][type]"
	    "[dns][answers][data]" => "[aws][answers][array][2][rdata]"    
	    "[dns][answers][class]" => "[aws][answers][array][2][class]"    
	  }
    }
  }

  # "[event][created]" = 1744115336775
  date {
    match => ["[event][created]" , UNIX_MS ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
   }
  mutate {
    remove_field => [ "aws" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
