# Copyright [2024] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate{
    remove_field => [ "host", "event" ]
  }
  mutate{
    add_field => { "[event][module]" => "axway" }
    add_field => { "[event][dataset]" => "axway.mft_securetransport-edge" }
  }
  json {
    source => "message"
    target => "tmp"
    skip_on_invalid_json => false
  }
  mutate {
    rename => {
      "[tmp][id][mconfigurationid]" => "[container][id]"
      "[tmp][id][meventid]" => "[event][id]"
      "[tmp][id][mtimestamp]" => "[event][created]"
      "[tmp][time]" => "[event][ingested]"
      "[tmp][id][urlrepresentation]" => "[url][path]"
      "[tmp][node]" => "[host][id]"
      "[tmp][level]" => "[log][level]"
      "[tmp][component]" => "[log][syslog][facility][name]"
      "[tmp][thread]" => "[process][name]"
      "[tmp][filename]" => "[file][name]"
      "[tmp][classname]" => "[event][category]"
      "[tmp][method]" => "[http][request][method]"
      "[tmp][line]" => "[log][origin][file][line]"
      "[tmp][message]" => "[error][message]"
      "[tmp][exception]" => "[rule][description]"
      "[tmp][metadata][links][self]" => "[url][full]"
    }
  }
  # "[tmp][message]" => "[error][message]" # "connected to /200.63.96.59:22"
     grok {
       match => { "[error][message]" =>  [
         '^(?<[event][action]>.*?) ((from:/(?<[source][ip]>\d+\.\d+\.\d+\.\d+):(?<[source][port]>\d+))|(to\s/(?<[destination][ip]>\d+\.\d+\.\d+\.\d+):(?<[destination][port]>\d+)))$',
         '^.*?version:(?<[http][version]>\d+) Command: (?<[http][request][method]>.*?) Host: (?<[source][ip]>\d+\.\d+\.\d+\.\d+).*?Port: (?<[destination][port]>\d+)',
         '^\[(?<[process][name]>.*?\]) \[accountName=(?<[user][name]>.*?)\] \[remoteAddress=/(?<[source][ip]>\d+\.\d+\.\d+\.\d+):(?<[source][port]>\d+)\]:(?<[error][message]>.*?(?<[event][action]>((S|s)uccess)|(attempt )|(logged out)).*?)$',
         '^(?<msg>Instantiating sync data manager) for "(?<[url][full]>.*?((?<[server][ip]>\d+\.\d+\.\d+\.\d+):(?<[server][port]>\d+))?)"',
         '^(?<[http][request][method]>(GET|POST|PUT|PoST)) (?<[event][action]>.*?) .*? resource: (?<[url][path]>.*?)(?<[url][query]>\?.*?),.*?name: (?<[user][name]>\w+).*?IP: (?<[source][ip]>\d+\.\d+\.\d+\.\d+)',
         '^(?<[event][action]>Result).*?resource: (?<[url][path]>.*?)(?<[url][query]>\?.*?), .*?name: (?<[user][name]>\w+) from IP: (?<[source][ip]>\d+\.\d+\.\d+\.\d+) - (?<http_response_status_code>\w+)',
         '^\w+\s+.*?(?<[event][action]>Session expired).*?name "(?<[user][name]>\w+)".*?from \[(?<[source][ip]>\d+\.\d+\.\d+\.\d+)',
         '^(?<[event][action]>Synchronization request) from (?<[source][ip]>\d+\.\d+\.\d+\.\d+).*?name "(?<[user][name]>\w+)"'
       ]

        }
      }


  # "[tmp][id][mtimestamp]": [event][created] 1729607988522
  date {
    match => [ "[event][created]" , "UNIX_MS" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }

  # "[tmp][time]" => "[event][ingested]" # "tue, 22 oct 2024 09:39:48 -0500"
  date {
    match => [ "[event][ingested]" , "EEE, dd MMM yyyy HH:mm:ss Z" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][ingested]"
    tag_on_failure => "_dateparsefailure_ei"
  }

  mutate {
    remove_field => [ "tmp",  "message" ]
  }

}
output {
  pipeline { send_to => [enrichments] }
}
