# Copyright [2021] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
# Azure Monitoring Agent for Linux syslog
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "linux" }
    add_field => { "[event][dataset]" => "linux.rsyslog" }
  }
  json {
    source => "message"
    target => "tmp"
  }
  mutate {
    rename => {
      "[tmp][Computer]" => "[log][source][hostname]"
      "[tmp][EventTime]" => "[event][created]" 
      "[tmp][Facility]" => "[log][syslog][facility][name]"
      "[tmp][HostIP]" => "[host][ip]"
      "[tmp][ProcessID]" => "[process][pid]"
      "[tmp][ProcessName]" => "[process][name]"
      "[tmp][SeverityLevel]" => "[log][syslog][severity][name]"
      "[tmp][SyslogMessage]" => "[error][message]"
      "[tmp][SourceSystem]" => "[host][type]"
      "[tmp][TenantId]" => "[cloud][account][id]"
      "[tmp][_Internal_WorkspaceResourceId]" => "[cloud][project][id]"
      "[tmp][_ItemId]" => "[cloud][instance][id]"
      "[tmp][_ResourceId]" => "[cloud][instance][name]"
      "[tmp][HostName]" => "[host][hostname]"
    }
  }
  # "[event][created]" "2024-05-30t13:41:52.0000000z",
  date {
    match => ["[event][created]", "ISO8601"]
    timezone => "GMT"
    locale => "ec"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}