# Copyright [2021] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "oracle" }
    add_field => { "[event][dataset]" => "oracle.db_audit" }
    copy => { "message" => "[log][original]" }
  }
  json {
    source => "message"
    target => "tmp"
    tag_on_failure => "_jsonparsefailure_init"
  }  
  mutate {
    rename => {
      "[tmp][Computer]" => "[log][source][hostname]"
      "[tmp][Type]" => "[log][type]"
      "[tmp][EventData][TimeGenerated]" => "[event][created]"
      "[tmp][_ResourceId]" => "[cloud][instance][name]"
      "[tmp][_ItemId]" => "[cloud][instance][id]"
      "[tmp][TenantId]" => "[cloud][account][id]"
      "[tmp][_Internal_WorkspaceResourceId]" => "[cloud][project][id]"
      "[tmp][FilePath]" => "[log][file][path]"
      "[tmp][RawData]" => "[error][message]"
    }
  }
  date {
    match => ["[event][created]", "ISO8601"]
    timezone => "GMT"
    locale => "ec"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }    
  json_encode {
    source => "tmp"
    target => "[event][original]"
  }
  if ![log][source][hostname] {
    grok {
      match => { "[cloud][instance][name]" => "^.*\/(?<[log][source][hostname]>.*?)$" }
    }
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}