# Copyright [2021] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "oracle" }
    add_field => { "[event][dataset]" => "oracle.db_audit" }
  }
  json {
    source => "message"
    target => "tmp"
    tag_on_failure => "_jsonparsefailure_init"
  }  
# lowercase field names
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => {
      "[tmp][host][name]" => "[log][source][hostname]"
      "[tmp][log][file][path]" => "[log][file][path]"
      "[tmp][message]" => "[error][message]"
      "[tmp][agent]" => "agent"
    }
  }
  grok {
    match => { "[error][message]" => "^(?<[event][created]>.*?)\n(?<[process][name]>.*?) \((PID|pid):(?<[process][pid]>\d+)\)" }
  }
  date {
    match => ["[event][created]", "ISO8601"]
    timezone => "GMT"
    locale => "ec"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}