# Copyright [2024] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
# https listener for boomi logs
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    add_field => { "[event][module]" => "boomi" }
    add_field => { "[event][dataset]" => "boomi.integration-platform" }
  }
}
output {
  pipeline { send_to => [enrichments] }
}