# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  # lowercase field names
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowercase_ruby_block"
  }
  json {
    source => "message"
    target => "tmp"
  }
  mutate {
    remove_field => ["[tmp][host]", "[tmp][event]" ]
  }
  mutate {
    add_field => { 
	    "[event][module]" => "citrix"
      "[event][dataset]" => "citrix.session" 
    }
    rename => { 
      "[tmp][clientname]" => "[source][address]"
      "[tmp][clientaddress]" => "[source][ip]"
      "[tmp][username]" => "[source][user][id]"
      "[tmp][usr_full_name]" => "[source][user][full_name]"
      "[tmp][usr_domain]" => "[source][user][domain]"
      "[tmp][connectedviaipaddress]" => "[source][nat][ip]"
      "[tmp][launchedviahostname]" => "[destination][address]"
      "[tmp][launchedviaipaddress]" => "[destination][nat][ip]"
      "[tmp][publishedname]" => "[service][ephemeral_id]"
      "[tmp][enabled]" => "[event][code]"
      "[tmp][protocol]" => "[network][protocol]"
      "[tmp][clientplatform]" => "[host][os][name]"
      "[tmp][id]" => "[event][id]"
      "[tmp][applicationtype]" => "[service][type]"
      "[tmp][browsername]" => "[user_agent][name]"
      "[tmp][connectedviahostname]" => "[server][address]"
      "[tmp][clientversion]" => "[host][os][version]"
      "[tmp][name]" => "[service][name]"
    }
  }
  # Converting date strings to date
  # "logonstartdate": "2023-12-01t04:53:44.787z",
  date {
    match => ["[tmp][logonstartdate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
  }
  # "establishmentdate": "2023-12-01t04:53:44.787z", 
  date {
    match => ["[tmp][establishmentdate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][ingested]"
  }
  # "createddate": "2023-12-01t04:53:44.787z", 
  date {
    match => ["[tmp][createddate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
