# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  lowercase field names
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowercase_ruby_block"
  }
  mutate {
    remove_field => ["[host]", "[event]" ]
  }
  mutate {
    add_field => { 
	    "[event][module]" => "citrix"
      "[event][dataset]" => "citrix.session" 
    }
    rename => { 
      "[clientname]" => "[source][address]"
      "[clientaddress]" => "[source][ip]"
      "[username]" => "[source][user][id]"
      "[usr_full_name]" => "[source][user][full_name]"
      "[usr_domain]" => "[source][user][domain]"
      "[connectedviaipaddress]" => "[source][nat][ip]"
      "[launchedviahostname]" => "[destination][address]"
      "[launchedviaipaddress]" => "[destination][nat][ip]"
      "[publishedname]" => "[service][ephemeral_id]"
      "[enabled]" => "[event][code]"
      "[protocol]" => "[network][protocol]"
      "[clientplatform]" => "[host][os][name]"
      "[id]" => "[event][id]"
      "[applicationtype]" => "[service][type]"
      "[browsername]" => "[user_agent][name]"
      "[connectedviahostname]" => "[server][address]"
      "[clientversion]" => "[host][os][version]"
      "[name]" => "[service][name]"
    }
  }
  # Converting date strings to date
  # "logonstartdate": "2023-12-01t04:53:44.787z",
  date {
    match => ["[logonstartdate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
  }
  # "establishmentdate": "2023-12-01t04:53:44.787z", 
  date {
    match => ["[establishmentdate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][ingested]"
  }
  # "createddate": "2023-12-01t04:53:44.787z", 
  date {
    match => ["[createddate]", "yyyy-MM-dd'T'HH:mm:ss.sss'Z'","yyyy-MM-dd't'HH:mm:ss.sss'z'", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
  }
}
output {
  pipeline { send_to => [enrichments] }
}
