# Copyright [2022] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
	remove_field => ["event", "host", "log","user" ]
  }
  mutate {
    add_field => { 
      "[event][module]" => "azure"
      "[event][dataset]" => "azure.azureactivity"
      "[log][source][hostname]" => "event_hub_azureactivity" 
    }
  }
  json {
      source => "message"
      target => "tmp"
      skip_on_invalid_json => true
  }
  mutate {
    rename => { 
      "[tmp][TenantId]" => "[cloud][account][id]"
      "[tmp][OperationNameValue]" => "[cloud][service][name]"
      "[tmp][SubscriptionId]" => "[cloud][project][id]"
      "[tmp][ResourceProviderValue]" => "[cloud][instance][name]"
      "[tmp][_Internal_WorkspaceResourceId]" => "[cloud][project][name]"
      "[tmp][_ResourceId]" => "[cloud][machine][type]"
      "[tmp][Properties_d][message]" => "[error][message]"
      "[tmp][ActivityStatusValue]" => "[event][action]"
      "[tmp][CategoryValue]" => "[event][category]"
      "[tmp][ActivitySubStatusValue]" => "[event][outcome]"
      "[tmp][_UniqueRecordId]" => "[event][id]"
      "[tmp][TimeGenerated]" => "[event][created]"
      "[tmp][CorrelationId]" => "[event][code]"
      "[tmp][HTTPRequest]" => "[http][request][body][content]"
      "[tmp][Level]" => "[log][level]"
      "[tmp][Properties_d][resource]" => "[process][name]"
      "[tmp][CallerIpAddress]" => "[source][ip]"
      "[tmp][Caller]" => "[user][id]"
      "[tmp][ResourceGroup]" => "[user][group][name]"
      "[tmp][Authorization_d][evidence][role]" => "[user][roles]"
    }
  }
  mutate {
    gsub => [
      "[http][request][body][content]", '"""', ""
	]
  }  
  # "[event][created]" "2024-01-18t10:15:44.3227741z"
    date {
    match => ["[event][created]" , "yyyy-MM-dd'T'HH:mm:ss.SSSSSSS'Z'" ]
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }

  mutate {
   remove_field => [ "tmp", "records", "az" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}