# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    add_field => { "[event][module]" => "azure" }
    add_field => { "[event][dataset]" => "azure.eventhub.security" }
    add_field => { "[agent][name]" =>  "azure.eventhub" }
    add_field => { "[log][source][hostname]" => "api_azure_eventhub_security" }
  }
  mutate {
    gsub => ["message" ," ",""]
  }
  json {
    source => "message"
    target => "azsec"
  }
  mutate {
    rename => {"[azsec][operationName]" => "[rule][name]"}
    rename => {"[azsec][properties][recommendationCategory]" => "[event][category]"}
    rename => {"[azsec][properties][recommendationImpact]" => "[event][severity_name]"}
    rename => {"[azsec][properties][recommendationName]" => "[event][recommendation]"}
    rename => {"[azsec][properties][recommendationSchemaVersion]" => "[rule][version]"}
    rename => {"[azsec][properties][recommendationResourceLink]" => "[event][reference]"}
    rename => {"[azsec][properties][recommendationType]" => "[event][type]"}
    rename => {"[azsec][resultSignature]" => "[error][code]"}
    rename => {"[azsec][resultType]" => "[event][action]"}
    rename => {"[azsec][level]" => "[log][level]"}
    rename => {"[azsec][resultDescription]" => "[rule][description]"}
    rename => {"[azsec][callerIpAddress]" => "[source][ip]"}
    rename => {"[azsec][category]" => "[rule][category]"}
    rename => {"[azsec][location]" => "[host][geo][name]"}
    rename => {"[azsec][time]" => "[event][start]"}
    rename => {"[azsec][operationVersion]" => "[host][os][version]"}
    rename => {"[azsec][durationMs]" => "[event][duration]"}
    rename => {"[azsec][alertUri]" => "[event][url]"}
  }
  mutate {
    remove_field => [ "[azsec]" ]
  }
  date {
    match => ["[event][start]" , "ISO8601"]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
    tag_on_failure => "_dateparsefailure_es"
  }

  if "_dateparsefailure_es" in [tags]  {
    mutate {
      remove_field => ["[event][start]"]
    }
  }
}
output {
  pipeline { send_to => [enrichments] }
}
