# Copyright [2021] [Cargill, Incorporated.] 
# SPDX-License-Identifier: Apache-2.0
# Ansible alert web hook to logstash https listener
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    add_field => { "[event][module]" => "hadoop" }
    add_field => { "[event][dataset]" => "hadoop.agent" }
    rename => { "[beat][hostname]" => "[log][source][hostname]" }
    update => { "message" => "%{[event][original]}" }
	remove_tag => [ "hadoop-log4j", "jobhistory", "beats", "beats_input_codec_plain_applied", "siem-kafka" ]
    rename => {
      "user" => "user_tmp"
      "destination" => "destination_tmp"
      "service" => "service_tmp"
    }
  }
  mutate {
    rename => {
      "@timestamp" => "[event][created]"
      "[input][type]" => "[file][type]"
      "program" => "[event][kind]"
      "source" => "[file][path]"
      "tags" => "[tags]"
      "severity" => "[event][severity_name]"
      "[beat][name]" => "[agent][name]"
      "[beat][hostname]" => "[host][hostname]"
      "[beat][version]" => "[agent][version]"
      "thread" => "[process][thread][id]"
      "role" => "[user][roles]"
      "[fields][environment]" => "[group][name]"
      "user_tmp" => "[user][name]"
      "destination_tmp" => "[file][target_path]"
      "service_tmp" => "[service][name]"
    }
  }
  
  date {
    match => [ "[event][created]", "ISO8601" ]
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
  # Issue: "user"=>{"name"=>{"roles"=>"daemon"}},  tmp remove field "[user][name]"
  mutate {
    remove_field => [ "beat" , "input", "topic_name", "offset", "@version", "fields", "prospector", "level", "[event][original]", "[user][name]"]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
