# Copyright [2025] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  ruby {
    code => '
      msg = event.get("message")
      if msg.is_a?(String)
        lines = msg.split(/\r?\n/).reject { |l| l.nil? || l.empty? }
        if lines.length > 1
          event.set("message", lines.shift)
          lines.each do |line|
            e = event.clone
            e.set("message", line)
            new_event_block.call(e)
          end
        elsif lines.length == 1
          event.set("message", lines[0])
        else
          event.cancel
        end
      end
    '
  }

  grok {
    match => {
      "message" => [
        '%{IPORHOST:[source][ip]} - - \[%{HTTPDATE:[kong][time_local]}\] "%{WORD:[http][request][method]} %{DATA:[url][original]} [Hh][Tt][Tt][Pp]/%{NUMBER:[http][version]}" %{INT:[http][response][status_code]} %{INT:[http][response][body][bytes]} "%{DATA:[http][request][referrer]}" "%{DATA:[user_agent][original]}"(?: kong_request_id: "%{DATA:[kong][request_id]}")?'
      ]
    }
  }

  mutate {
    replace => { "[event][module]" => "kong" }
    replace => { "[event][dataset]" => "kong.gateway" }
    lowercase => ["[http][request][method]"]
    convert => {
      "[http][response][status_code]" => "integer"
      "[http][response][body][bytes]" => "integer"
    }
  }
}
output {
  pipeline { send_to => [enrichments] }
}
