# Copyright [2023] [Cargill, Incorporated.]
# SPDX-License-Identifier:  Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { 
      "[event][module]" => "aws_security_lake"
      "[event][dataset]" => "aws_security_lake.security_hub"
      "[log][source][hostname]" => "security_lake" 
    }
  }
  json {
    source => "message"
    target => "tmp"
    skip_on_invalid_json => false
  }
  # lowercase field names
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => {
      "[tmp][metadata][product][name]" => "[event][kind]"
      "[tmp][time]" => "[event][created]"
      "[tmp][resource][type]" => "[cloud][machine][type]"
      "[tmp][resource][uid]" => "[cloud][account][id]"
      "[tmp][resource][cloud_partition]" => "[cloud][provider]"
      "[tmp][resource][region]" => "[cloud][region]"
      "[tmp][finding_info][uid]" => "[rule][uuid]"
      "[tmp][finding_info][desc]" => "[rule][description]"
      "[tmp][finding_info][title]" => "[rule][name]"
      "[tmp][finding_info][created_time_dt]" => "[event][ingested]"
      "[tmp][finding_info][modified_time_dt]" => "[event][modified]"
      "[tmp][finding_info][first_seen_time_dt]" => "[event][start]"
      "[tmp][finding_info][last_seen_time_dt]" => "[event][end]"
      "[tmp][finding_info][types][array]" => "[rule][ruleset]"
      "[tmp][remediation][desc]" => "[vulnerability][description]"
      "[tmp][remediation][references][array]" => "[vulnerability][reference]"
      "[tmp][category_name]" => "[rule][category]"
      "[tmp][category_uid]" => "[rule][id]"
      "[tmp][severity_id]" => "[event][severity]"
      "[tmp][severity]" => "[event][severity_name]"
      "[tmp][activity_name]" => "[event][action]"
      "[tmp][status]" => "[event][outcome]"
      "[tmp][type_name]" => "[event][type]"
      "[tmp][resource][data]" => "[event][original]"
    }
  }
# 1682551328591
  
  date {
    match => ["[event][created]", "UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
    tag_on_failure => "_dateparsefailure_ec"
  }
  date {
    match => ["[event][ingested]", "UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][ingested]"
    tag_on_failure => "_dateparsefailure_ei"
  }
   date {
    match => ["[event][modified]", "UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][modified]"
    tag_on_failure => "_dateparsefailure_em"
  } 
   date {
    match => ["[event][start]", "UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][start]"
    tag_on_failure => "_dateparsefailure_es"
  } 
   date {
    match => ["[event][end]", "UNIX_MS"]
    timezone => "GMT"
    locale => "en"
    target => "[event][end]"
    tag_on_failure => "_dateparsefailure_ee"
  } 

  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}