# Copyright [2025] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  ruby {
    code => '
      msg = event.get("message")
      if msg.is_a?(String)
        lines = msg.split(/\r?\n/).reject { |l| l.nil? || l.empty? }
        if lines.length > 1
          event.set("message", lines.shift)
          lines.each do |line|
            e = event.clone
            e.set("message", line)
            new_event_block.call(e)
          end
        elsif lines.length == 1
          event.set("message", lines[0])
        else
          event.cancel
        end
      end
    '
  }
  if [message] =~ /upstream:/ {
    dissect {
      mapping => {
        "message" => '%{tmp_log_time} [%{tmp_log_level}] %{?pid}: *%{?tmp_connection} %{tmp_error_message}, client: %{tmp_source_ip}, server: %{tmp_server_name}, request: "%{tmp_method} %{tmp_url_path} %{tmp_http_proto}", upstream: "%{tmp_upstream}", host: "%{tmp_host}", request_id: "%{tmp_request_id}"'
      }
    }
  }
  else if [message] =~ /^\d{4}\/\d{2}\/\d{2}/ {
    dissect {
      mapping => {
        "message" => '%{tmp_log_time} [%{tmp_log_level}] %{?pid}: *%{?tmp_connection} [kong] %{?file} %{tmp_error_message}, client: %{tmp_source_ip}, server: %{tmp_server_name}, request: "%{tmp_method} %{tmp_url_path} %{tmp_http_proto}", host: "%{tmp_host}", request_id: "%{tmp_request_id}"'
      }
    }
  } else {
    dissect {
      mapping => {
        "message" => '%{tmp_source_ip} - %{tmp_remote_user} [%{tmp_time_local}] "%{tmp_method} %{tmp_url_path} %{tmp_http_proto}" %{tmp_status_code} %{tmp_body_bytes} "%{tmp_referrer}" "%{tmp_user_agent}"%{tmp_tail}'
      }
    }
    if [tmp_tail] =~ /^ kong_request_id: "/ {
      dissect {
        mapping => {
          "tmp_tail" => ' kong_request_id: "%{tmp_request_id}"'
        }
      }
    }
  }

  dissect {
    mapping => {
      "tmp_http_proto" => "%{tmp_http_scheme}/%{tmp_http_version}"
    }
  }

  if [tmp_remote_user] == "-" {
    mutate {
      remove_field => ["tmp_remote_user"]
    }
  }

  if [tmp_user_agent] == "-" {
    mutate {
      remove_field => [ "tmp_user_agent" ]
    }
  }

  if [tmp_referrer] == "-" {
    mutate {
      remove_field => [ "tmp_referrer" ]
    }
  }

  mutate {
    rename => {
      "tmp_source_ip" => "[source][ip]"
      "tmp_time_local" => "[kong][time_local]"
      "tmp_method" => "[http][request][method]"
      "tmp_url_original" => "[url][original]"
      "tmp_http_version" => "[http][version]"
      "tmp_status_code" => "[http][response][status_code]"
      "tmp_body_bytes" => "[http][response][body][bytes]"
      "tmp_referrer" => "[http][request][referrer]"
      "tmp_user_agent" => "[user_agent][original]"
      "tmp_request_id" => "[kong][request_id]"
      "tmp_log_time" => "[event][created]"
      "tmp_log_level" => "[log][level]"
      "tmp_error_message" => "[error][message]"
      "tmp_host" => "[host][name]"
      "tmp_server_name" => "[server][name]"
      "tmp_url_path" => "[url][path]"
      "tmp_remote_user" => "[user][name]"
      "tmp_upstream" => "[url][full]"
    }
    replace => { "[event][module]" => "kong" }
    replace => { "[event][dataset]" => "kong.gateway" }
    lowercase => ["[http][request][method]"]
    remove_field => ["tmp_tail", "tmp_http_proto", "tmp_http_scheme"]
  }
  
  date {
    match => ["[event][created]", "YYYY/MM/dd HH:mm:ss"]
    target => "[event][created]"
  }
}
output {
  pipeline { send_to => [enrichments] }
}
