# Copyright [2025] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  ruby {
    code => '
      msg = event.get("message")
      if msg.is_a?(String)
        lines = msg.split(/\r?\n/).reject { |l| l.nil? || l.empty? }
        if lines.length > 1
          event.set("message", lines.shift)
          lines.each do |line|
            e = event.clone
            e.set("message", line)
            new_event_block.call(e)
          end
        elsif lines.length == 1
          event.set("message", lines[0])
        else
          event.cancel
        end
      end
    '
  }

  dissect {
    mapping => {
      "message" => '%{tmp_source_ip} - - [%{tmp_time_local}] "%{tmp_method} %{tmp_url_original} %{tmp_http_proto}" %{tmp_status_code} %{tmp_body_bytes} "%{tmp_referrer}" "%{tmp_user_agent}"%{tmp_tail}'
    }
  }

  dissect {
    mapping => {
      "tmp_http_proto" => "%{tmp_http_scheme}/%{tmp_http_version}"
    }
  }

  if [tmp_tail] =~ /^ kong_request_id: \"/ {
    dissect {
      mapping => {
        "tmp_tail" => ' kong_request_id: "%{tmp_request_id}"'
      }
    }
  }

  mutate {
    rename => {
      "tmp_source_ip" => "[source][ip]"
      "tmp_time_local" => "[kong][time_local]"
      "tmp_method" => "[http][request][method]"
      "tmp_url_original" => "[url][original]"
      "tmp_http_version" => "[http][version]"
      "tmp_status_code" => "[http][response][status_code]"
      "tmp_body_bytes" => "[http][response][body][bytes]"
      "tmp_referrer" => "[http][request][referrer]"
      "tmp_user_agent" => "[user_agent][original]"
      "tmp_request_id" => "[kong][request_id]"
    }
    replace => { "[event][module]" => "kong" }
    replace => { "[event][dataset]" => "kong.gateway" }
    lowercase => ["[http][request][method]"]
    remove_field => ["tmp_tail", "tmp_http_proto", "tmp_http_scheme"]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
