# Copyright [2025] [Cargill, Incorporated.]
# SPDX-License-Identifier: Apache-2.0
input {
  pipeline {
    address => VAR_PIPELINE_NAME
  }
}
filter {
  mutate {
    remove_field => [ "event", "host" ]
  }
  mutate {
    add_field => { "[event][module]" => "ionix" }
    add_field => { "[event][dataset]" => "ionix.alert" }
    add_field => { "[log][source][hostname]" => "ionix_webhook" }
  }
  json {
    source => "message"
    target => "tmp"
  }
  ruby {
    path => "${LOGSTASH_HOME}/config/lower.rb"
    tag_on_exception => "_lowecase_ruby_block"
  }
  mutate {
    rename => {
      "[tmp][results][id]" => "[event][id]"
      "[tmp][results][urgency][urgency]" => "[event][severity]"
      "[tmp][results][urgency][type" => "[event][type]"
      "[tmp][results][updated_time]" => "[event][created]"
    }
  }
  # "2025-05-15T18:35:37.021Z"
  date {
    match => [ "[event][created]", "ISO8601" ]
    timezone => "GMT"
    locale => "en"
    target => "[event][created]"
  }
  mutate {
    remove_field => [ "tmp" ]
  }
}
output {
  pipeline { send_to => [enrichments] }
}
